### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by aking4125** [ACGaming/BattleTowersFixes#2]
Hello,

I'm not sure what is going on but all of a sudden this mod crashes with Battle Towers even though it's installed. Removing this mod allows the pack to load with the battle towers working normally. It was working before now it isn't.

_Update: Using Prism Launcher 8 here, it allows to check for mod updates. I must've pushed an update for this and didn't notice. This seems to only occur on BT Fixes 1.2.1. 1.2.0 works._

https://mclo.gs/kzKtKND

Any ideas?

**Comment by ACGaming** [comment]
Resolved in e8658973dfeb190c30c5216e7c64a6a3fe315746
